language: node_js
node_js:
- '0.12'
- '4'
sudo: false
deploy:
  provider: heroku
  api_key:
    secure: EzrSIqqULIoSkIK/GWKdhQ84XlMBOkOzLho2Ei4DpKTUpM9kW5kU0oAzpw4EUORUEKnkTQWwdnDvmsOPBWdL/lMY6SXMdIGG2wf1HEVqjg0Xceq0LrqjUBoMuPgHWjXBKNgobU6uIYpfgQPxHLFqaJvlTNfVydJ52v6S2IXND54=
  app:
    master: webmaker-desktop-production
    develop: webmaker-desktop-staging
  on:
    repo: mozilla/webmaker-browser
    node: '0.12'
